#!groovy
@Library('jenkins-shared-library') _

properties([
  parameters([
    string(name: 'region', defaultValue: 'us-east-1', description: 'AWS Region'),    
   ])
])

def region = params.region

cloudformation_pipeline {
    region        = region
    stackName     = 'security-groups'
    appTag        = 'network-infrastructure'
    templateFile  = '01-networking/security-groups/template.yml'
}