AWSTemplateFormatVersion: "2010-09-09"
Description: VPC

Parameters:
  AppTag:
    Type: String
    Default: 'network-infrastructure'

Resources:

  PublicSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: 'publicsg'
      GroupDescription: 'WARNING: Allowing 22 from anywhere'
      VpcId: !ImportValue 'vpc-VPCID'
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0

  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: 'dbsecuritygroup'
      GroupDescription: 'WARNING: Allowing from anywhere'
      VpcId: !ImportValue 'vpc-VPCID'
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 5432
        ToPort: 5432
        CidrIp: 0.0.0.0/0

Outputs:
  PublicSecurityGroup:
    Description: Public Security Group Id
    Value: !Ref PublicSecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-PublicSG"
  DBSecurityGroup:
    Description: DB Security Group Id
    Value: !Ref DBSecurityGroup
    Export:
      Name: !Sub "${AWS::StackName}-DBSG"