AWSTemplateFormatVersion: "2010-09-09"
Description: ECR Repo

Parameters:
  AppTag:
    Type: String
    Default: 'repo-infrastructure'

Resources:
  AppRepository: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: "credential-registry"
      ImageTagMutability: 'IMMUTABLE'
      RepositoryPolicyText: 
        Version: "2012-10-17"
        Statement: 
          - 
            Sid: AllowPushPull
            Effect: Allow
            Principal: 
              AWS: 
                - !Sub "arn:aws:iam::${AWS::AccountId}:user/cloudformation"
            Action: 
              - "ecr:*"
  AppDevelopmentRepository: 
    Type: AWS::ECR::Repository
    Properties: 
      RepositoryName: "credential-registry-snapshots"
      ImageTagMutability: 'MUTABLE'
      LifecyclePolicy: 
        LifecyclePolicyText:
          rules:
            - rulePriority: 1
              description: 'untagged images'
              selection:
                tagStatus: untagged
                countType: sinceImagePushed
                countUnit: 1
                countNumber: 1
          
      RepositoryPolicyText: 
        Version: "2012-10-17"
        Statement: 
          - 
            Sid: AllowPushPull
            Effect: Allow
            Principal: 
              AWS: 
                - !Sub "arn:aws:iam::${AWS::AccountId}:user/cloudformation"
            Action: 
              - "ecr:*"
