AWSTemplateFormatVersion: "2010-09-09"
Description: VPC

Parameters:
  AppTag:
    Type: String
    Default: 'network-infrastructure'

Resources:
  MainVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16
      EnableDnsSupport: 'true'
      EnableDnsHostnames: 'true'
      Tags:
      - Key: app
        Value: !Sub '${AppTag}'
      - Key: Name
        Value: MainVPC

Outputs:
  MainVPC:
    Description: VPC
    Value: !Ref MainVPC
    Export:
      Name: !Sub "${AWS::StackName}-VPCId"