#!groovy
@Library('jenkins-shared-library') _

properties([
  parameters([
    string(name: 'region', defaultValue: 'us-east-1', description: 'AWS Region'),    
   ])
])

def region = params.region

cloudformation_pipeline {
    region        = region
    stackName     = 'redis-cluster'
    appTag        = 'database'
    templateFile  = '05-database/redis/template.yml'
}